######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 11:30:40 2012
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

DEFINES += UNICODE
DEFINES += _UNICODE

CONFIG += console

PRECOMPILED_HEADER = stable.h

# Input
HEADERS += color.h
HEADERS += sigslot.h
HEADERS += test.h

SOURCES += main.cpp

